#!/bin/bash

set -eux

BUILD_FOR=${BUILD_FOR:-ubuntu}
DIR="$(dirname `readlink -f $0`)"
TMP=${DIR}/tmp

INCLUDE_DEPENDENCIES=${INCLUDE_DEPENDENCIES:-true}
http_proxy=${http_proxy}
https_proxy=${https_proxy}
ovs_ref=${ovs_ref:-master}
dpdk_ref=${dpdk_ref:-2.1.0}
networking_ovs_dpdk=${networking_ovs_dpdk:-master}

rm -rf ${TMP}
mkdir -p ${TMP}
rm -rf ${DIR}/repositories/${BUILD_FOR}/*

# We need git to clone networking-ovs-dpdk repo
apt-get install -y git

# sudo apt-get install -qq --reinstall --print-uris bash | perl -lne "/'(.*?)'/;print \$1"
if [ "$INCLUDE_DEPENDENCIES" = true ]
then
  wget --content-disposition -N -P ${DIR}/repositories/${BUILD_FOR}/ -i "${DIR}/ovs_package/${BUILD_FOR}/dependencies.txt"
fi

wget https://github.com/openvswitch/ovs/archive/${ovs_ref}.zip -O ${DIR}/repositories/${BUILD_FOR}/ovs.zip
wget http://www.dpdk.org/browse/dpdk/snapshot/dpdk-${dpdk_ref}.zip -O ${DIR}/repositories/${BUILD_FOR}/dpdk.zip

rm -rf ${TMP}/networking-ovs-dpdk
git clone https://github.com/openstack/networking-ovs-dpdk ${TMP}/networking-ovs-dpdk
cd ${TMP}
zip -r ${DIR}/repositories/${BUILD_FOR}/networking-ovs-dpdk.zip networking-ovs-dpdk/* 

rm -rf ${TMP}

#wget https://github.com/openstack/networking-ovs-dpdk/archive/${networking_ovs_dpdk}.zip -O ${DIR}/repositories/${BUILD_FOR}/networking_ovs_dpdk.zip 
